---

- hosts: all
  become: true
  tasks:


  - name: Update repository index + install Apache + PHP  packages for Ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
