- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache  

- name: copy htmp file for site
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
